### ISSUE TITLE
How to access output of Matlab function in other tasks? 

### ISSUE THREAD

**Issue by bavodenys** [mathworks/matlab-azure-devops-extension#100]
Hi

I have a Azure pipeline with a task to open a project in Matlab and to run a Matlab script (fcnBuildAll) to build my application. How can I access the output of the function fcnBuildAll() and use it in the task PublishArtifacts? I like to use BuildSuccess in the condition section of PublishBuildArtifacts to only publish if the build was successful. How should I modify this section of code to have the desired functionality? Thanks in advance!

 - task: RunMATLABCommand@0
      inputs:
        command: |
          proj = openProject("proj.prj");
          BuildSuccess = fcnBuildAll();

- task: PublishBuildArtifacts@1
      condition: 
      inputs:
        PathtoPublish: './Utils/Installer'
        ArtifactName: 'Installer'
        publishLocation: 'Container'

**Comment by mcafaro** [comment]
Hi,

You can set variables in Azure Pipelines by printing a specially formatted string to the log (via the MATLAB `disp` command for example). See the [Set variables in scripts](https://learn.microsoft.com/en-us/azure/devops/pipelines/process/set-variables-scripts?view=azure-devops&tabs=bash) documentation for more details.

Below is an example of setting a pipeline variable in MATLAB and using it in a subsequent task condition (ported from [this Azure Pipelines documentation example](https://learn.microsoft.com/en-us/azure/devops/pipelines/process/conditions?view=azure-devops&tabs=yaml%2Cstages#use-the-pipeline-variable-created-from-a-step-in-a-condition-in-a-subsequent-step)):

```yaml
  # This step creates a new pipeline variable: doThing. This variable will be available to subsequent steps.
  - task: RunMATLABCommand@0
    inputs:
      command: |
        myvalue = "Yes";
        disp("##vso[task.setvariable variable=doThing]" + myvalue);

  # This step is able to use doThing in its condition as well as its body
  - script: |
      # You can access the variable from Step 1 as an environment variable.
      echo "Value of doThing (as DOTHING env var): $DOTHING."
    condition: and(succeeded(), eq(variables['doThing'], 'Yes'))
```

Best,
Mark
