### ISSUE TITLE
Toolbox support

### ISSUE THREAD

**Issue by agahkarakuzu** [mathworks/matlab-azure-devops-extension#39]
I wanted to give Azure extension a try, but looks like some essential toolboxes are missing:

![image](https://user-images.githubusercontent.com/9632322/104541437-9fb64780-55ef-11eb-9841-348881742b49.png)

I thought only transformation products were excluded on Microsoft Hosted Agents. Is this also the case with all the toolboxes, or do I need an extra configuration step for, let say, optimization and image processing toolboxes. 

Thanks!

Update: 

I run `ver` and saw that all the toolboxes are available! The problem is then:

```
result = license('test','Optimization_Toolbox');
```

which I assume has to do with the license is issued. Unless there is not another option, I will set an environment variable to bypass these checks on Azure.

**Comment by agahkarakuzu** [comment]
When I kept playing with the pipeline a bit more, I noticed that there is an unexpected behaviour: 

In `startup.m`
```octave
L1 if isempty(getenv('ISAZURE')) || ~str2double(getenv('ISAZURE')) 
L2        ISAZURE=false; 
L3    else
L4        ISAZURE=true; 
L5 end
L6 disp(['Azure env is' getenv('ISAZURE')]);
L7 if ~ISAZURE
L8      if ~license('test', 'Optimization_Toolbox'), error('Optimization Toolbox is not installed on your system: most qMR models won''t fit. Please consider installing <a href="matlab:matlab.internal.language.introspective.showAddon(''OP'');">Optimization Toolbox</a> if you want to use qMRLab in MATLAB.'); end
L9      if ~license('test', 'Image_Toolbox'), warning('Image Toolbox is not installed: ROI Analysis tool not available in the GUI. Consider installing <a href="matlab:matlab.internal.language.introspective.showAddon(''IP'');">Image Processing Toolbox</a>'); end
L10 end
```
with the following Azure task:
```yaml
jobs:
- job: Ubuntu_MATLAB
  pool:
    vmImage: 'Ubuntu-16.04'
  steps:
    - checkout: self
      fetchDepth: 1
    - task: InstallMATLAB@0
    - task: RunMATLABCommand@0
      displayName: Run qMRLab
      inputs:
        command: |
          setenv('ISAZURE','1');
          act = pwd;
          ls;
          startup;
          qMRLabVer;
          disp('Test Done');
          exit;
```

produces the following log:
![image](https://user-images.githubusercontent.com/9632322/104545044-24f12a80-55f7-11eb-92c5-6da65c5720c9.png)

Normally it should not have stepped into the logical statement at `L7`, given that I pass `setenv('ISAZURE','1');` in the config. In addition, `Azure env is` was shown without the value of the set env variable, which is displayed properly later on.

The tasks from `qMRLabVer` on proceeds properly and can use toolboxes. Is there something wrong in the `yaml` task that tampers with the execution order?
